### ISSUE TITLE
Letodbf 2017-03-24 15:00 UTC+0100 Warning

### ISSUE THREAD

**Issue by ItamarLins** [elchs/LetoDBf#1]
'''
hbmk2: Compilando...
../../../../source/server/letovars.c: In function 'HB_FUN_LETO_VARGETLIST':
../../../../source/server/letovars.c:390:17: warning: null pointer dereference [
-Wnull-dereference]
             if( *pVar )
                 ^~~~~
'''

Best regards,
Itamar M. Lins Jr.

**Comment by elchs** [comment]
Hi Itamar,

sure rarely used: this is the Leto_VarGetList() used by UDF functions,
bug was inherited from origin.
Fixed also a memory issue in that function.

best regards
Rolf
