### ISSUE TITLE
Warning while make rddleto.hbp

### ISSUE THREAD

**Issue by ItamarLins** [elchs/LetoDBf#10]
Hi!
```
../../../../source/client/leto1.c:1204:12: warning: this statement may fall thro
ugh [-Wimplicit-fallthrough=]
          if( pField->uiLen == 4 )
            ^
../../../../source/client/leto1.c:1210:7: note: here
       case HB_FT_MODTIME:
       ^~~~
```
Best regards,
Itamar M. Lins Jr.

**Comment by elchs** [comment]
Hi Itamar,

a warning, aka logic was okay to spare redundant code -- but as missing 'breaks' have been so often a cause for 'unwanted' behavior, let the compiler [not more] warn ...

Thanks!,
Rolf
