### ISSUE TITLE
Letodbf return wrong position 

### ISSUE THREAD

**Issue by ItamarLins** [elchs/LetoDBf#11]
Hi!
index on xyz tag temp for date<... temporary 
Do While !eof()  //letodbf fail it enter in "DO WHILE" pointer fail return eof() = .F.
...
and now I "add" modify my line this with "gotop"
index on xyz tag temp for date<... temporary 
dbgotop() //Here now I am put this.
Do While !eof()  //letodbf ok skip do while pointer return eof() = .T.

Best regards,
Itamar M. Lins Jr.

**Comment by elchs** [comment]
Hi dear Itamar,

the record position was quite correct after index order create,
but the <workarea-flags> like EOF() [ BOF, FOUND ] were not re-set.
( aka an EOF before index create remained afterwards ... )

THANKS! for report -- a real bug -- should be fixed ...

best! regards
Rolf
