### ISSUE TITLE
DOS error 53 on SET(_SET_PRINTFILE, cPath + "TESTE.TXT", .F.)

### ISSUE THREAD

**Issue by vcatafesta** [elchs/LetoDBf#12]
Hello,
Initially, congratulate him for contributions in the community.
When using SET (_SET_PRINTFILE, cPath + "TEST.TXT", .F.), In the LetoDbf environment, I get a

Error TERM / 2014 Create error: //127.0.0.1:2812/TESTE.TXT
                      (DOS Error 53)

                Quit Retry Default

Is this a real mistake?
greetings

**Comment by elchs** [comment]
Hi Vilmar,

no bug or mistake -- but it is explain-able not working this way.

---
LetoDBf is a RDD ( Replaceable Database Driver ),
means it will take care of all your *DBF* related actions.

Further it offer Leto_F*() file functions,
to (manually!) deal with other file-types at the server.
*But* it will not re-direct any local file-access of Harbour to the server.

This is here the case:
the 'print-file' handle refer to a local file at client! file-system.
And your OS is not happy about filename: "//127.0.0.1:2812/TESTE.TXT"
No wonder: at least these <//> or <:> are known to make trouble ... ;-)

---
Workaround:
print to a valid file[name] valid at the client.
If this result is needed afterwards at server, to be processed by others,
we have to upload it with some function, and others then have to download.

( Readme.txt, chapter 7.6: e.g. Leto_FCopyToSrv() ... )

best regards
Rolf
