### ISSUE TITLE
Warning Compilations last commit

### ISSUE THREAD

**Issue by asimoesluz** [elchs/LetoDBf#13]
I updated letodbf yesterday and compiled letodb.exe
the compilation presented these warnings

hbmk2: Harbour: Compilando módulos...
hbmk2: Compilando recursos...
hbmk2: Compilando...
../../../../source/server/letofunc.c: In function 'leto_dbEvalJoinAdd':
../../../../source/server/letofunc.c:7445:39: warning: ?: using integer constants in boolean context [-Wint-in-bool-context]
       if( s_iDebugMode > ! bValid ? 0 : 20 )
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../../../../source/server/letofunc.c: In function 'HB_FUN_LETO_DBEVAL':
../../../../source/server/letofunc.c:8230:37: warning: ?: using integer constants in boolean context, the expression will always evaluate to 'true' [-Wint-in-bool-context]
       if( s_iDebugMode > bValid ? 1 : 20 )
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

**Comment by elchs** [comment]
old, non harmful warning, long ago fixed
