### ISSUE TITLE
LetoDbf fail with "locate" command

### ISSUE THREAD

**Issue by ItamarLins** [elchs/LetoDBf#14]
Hi!

RddSetDefault("LETO")
 ``Locate FOR cCriptSenha=us->senha .and. cCriptApelido=us->apelido``
This up command not working with atual version of letodbf

Works fine with rddsetdefault("DBFCDX")

Best regards,
Itamar M. Lins Jr.

**Comment by elchs** [comment]
fixed - verified by Itamar
