### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by carles9000** [elchs/LetoDBf#16]
Hi 

i try to compile with make_b32.bat

I've this errors

> 
> MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
> 	bcc32 -c -Iinclude;c:\hal\harbour.320\include -d   -tWM -D__WIN32__ -D__CONSOLE__  -DUSE_PMURHASH=1 -oobj\b32\letocl.obj source\client\letocl.c
> Borland C++ 5.82 for Win32 Copyright (c) 1993, 2005 Borland
> source\client\letocl.c:
> Error E2227 source\client\letocl.c 1276: Extra parameter in call to hb_znetFlush in function leto_Send
> Warning W8065 source\client\letocl.c 1291: Call to function 'hb_socketSetError' with no prototype in function leto_Send
> Warning W8065 source\client\letocl.c 1319: Call to function 'hb_socketSetError' with no prototype in function leto_DataSendRecv
> Warning W8065 source\client\letocl.c 1335: Call to function 'hb_socketSetError' with no prototype in function leto_DataSendRecv
> Warning W8065 source\client\letocl.c 3270: Call to function 'hb_fsPipeWrite' with no prototype in function LetoConnectionClose
> *** 1 errors in Compile ***
> 
> ** error 1 ** deleting obj\b32\letocl.obj

**Comment by elchs** [comment]
Hi,

a:) "make_b32.bat" is left for very experienced users,
it can be used to build the C-API client -- i bet !, that is not what you want.
Please check "Readme.txt" : 2.1 how to use "hbmk2"

b:) *one* error: ... extra parameter in call to hb_znetFlush ...
Parameter was added in Harbour 3.2 at: 2015/08/26.
The error indicates that your Harbour 3.2 is outdated,
and that also would explain the other *warnings*.

Ways to go:
a) update your Harbour 3.2 -- if problems show up in Harbour user group:
https://groups.google.com/forum/#!forum/harbour-users

b) there is a flag: `__HARBOUR30__` for building LetoDBf with Harbour !3.0!
i very would not recommend using that, you will miss functionality/ advantages of 3.2

best regards
Rolf

**Comment by carles9000** [comment]
Rolf,

I will follow your advice and try to do it.

I was testing the original of Mr. Alexander Kresin and everything was well compiled the first time. But 3 days ago I saw your fork and it seems more powerful and is very well commented. I will try to see the differences between the two. (If I can compile this fork ...)

Thanks for your advice and I'm sorry.
Carles
