### ISSUE TITLE
LetoDbf crashing with field memo FPT.

### ISSUE THREAD

**Issue by ItamarLins** [elchs/LetoDBf#2]
Hi!
Is there happening here errors when I am opening dbf with fields memo FPT.
It is difficult to isolate the problem.
The error occurs in specific records.

Best regards,
Itamar M. Lins Jr.

**Comment by ItamarLins** [comment]
More info.
Application Internal Error - C:\fontes\SCI_WIN\sciwin.exe
Terminated at: 2017-03-30 10:22:22
Unrecoverable error 9006: hb_xgrab can't allocate memory
Called from DBSEEK(0)
...
Application Internal Error - C:\fontes\SCI_WIN\sciwin.exe
Terminated at: 2017-03-30 10:27:18
Unrecoverable error 6005: Exception error:
Called from ORDSCOPE(0)
...
Best regards,
Itamar M. Lins Jr.

**Comment by ItamarLins** [comment]
Hi!
Here is the file:

**Comment by ItamarLins** [comment]
Hi!
Here is the file.
https://drive.google.com/open?id=0B1MfEZ3uuAPhSmdDTUhLUnp3RUU

Best regards,
Itamar M. Lins Jr.

**Comment by ItamarLins** [comment]
Hi!
```
#include "rddleto.ch"
Function main
setmode(25,80)
Set AutOpen On
set dele on

leto_Connect( '//localhost:2812/' )
DbUseArea(.T.,"LETO",'estoqobs.dbf',,.T.,.F.)
go top
do while .not. eof()
 ? observacao
 skip
EndDo
close all
return .t.
```
![letodbfcrash](https://cloud.githubusercontent.com/assets/3923502/24516311/8a93d766-1550-11e7-9eb0-319d51721e67.jpg)

**Comment by elchs** [comment]
Hi Itamar,

what a fundamental BUG, related to any! memofield with a size of 45 or multiple of that.
MANY THANKS for pointing it out -- fix was as easy as silly the bug was

MANY THANKS
Rolf
