### ISSUE TITLE
Randomly getting Unrecoverable error 9201: hb_cdxPageSeekKey: wrong parent key.  

### ISSUE THREAD

**Issue by mauriciofaria** [elchs/LetoDBf#23]
I am getting this error randomly running Letodbf server in a Windows Server 2019:

`Unrecoverable error 9201: hb_cdxPageSeekKey: wrong parent key. `

In a simple `seek` command.
Letodbf server and client app crash.
I have to re-create the index file in order to be back in business.
In a Windows Server 2008 environment, it used to occur once a week or less, but in W2019 it occurs almost every day, sometimes twice a day...
I found very few references about this error and none of them helped.
The last one 
Tables are shared between Letodbf and other exes executed via RDP Terminal services (so, local access), but all of them are part of the same (big) system.
A whole message sample in :
```
Breakdown at: 2022.05.20 10:37:28.712
Unrecoverable error 9201: hb_cdxPageSeekKey: wrong parent key.  
------------------------------------------------------------------------
User: 10.5.2.109 SVLABTS balan.exe  connection 14
Command: seek <e;24;A;640557    20220583>
Table: ACE354.001
```
Almost all the time its in the same table named ACE354.001 ( its extension is 001 but this is a regular DBF created and used only from Harbour ) with only C, N, and L fields, no memos.
From time to time it affects ( rarely ) another table.

A thing that is interesting is that it crashs when the system is working when many people is working on it, near the pike of users.
When fewer users are in it never goes down.
Taking this in mind, the reference I found in the internet that was closely related with the issue was [https://github.com/harbour/core/issues/60](https://github.com/harbour/core/issues/60).
I tried to change Windows System Memory parameters listed in quoted article,  [MS KB article](https://support.microsoft.com/en-us/help/304101/backup-program-is-unsuccessful-when-you-back-up-a-large-system-volume) with no success.

The Letodbf INI is:
```
Server = 127.0.0.1
Port = 2812
DataPath = C:\Folder
LogPath = C:\Folder\LetoLogs
Default_Driver = CDX
Lock_Scheme = 3
Memo_Type = FPT
Share_Tables = 1
No_Save_WA = 1
Lower_Path = 0
EnableFileFunc = 1
EnableAnyExt = 1
Allow_UDF = 1
Pass_for_Login = 0
Pass_for_Manage = 0
Pass_for_Data = 0
;Pass_File = "leto_users"
Cache_Records = 21
;Max_Vars_Number = 1000
;Max_Var_Size = 67108864
Tables_Max  = 2999
;Users_Max = 99
Debug = 2
Optimize = 1
;AutOrder = 0
;ForceOpt = 0
;TimeOut = 360
;Zombie_Check = 0
;Server_User = advantage
;Server_UID = 1000
;Server_GID = 4
DataBase = /
;Backup = /tmp/backup
Mask = *.dbf,*.dbt,*.ntx
Lock = 1
Seconds = 30
Wait = 1
;ArcCmd = tar -cvzf /tmp/backup/leto.tar.gz /tmp/backup/*
```
I am stucked and out of options and any help will be appreciated.

**Comment by prgwiz** [comment]
Did you disable virus scanning in the DBF directory?
Maybe some of the oplock settings may help?
Scandisk?
Server load ok?

**Comment by mauriciofaria** [comment]
Hi Gerald.

> Did you disable virus scanning in the DBF directory?
Yes, virus detection is disabled for the data files on the system directory.

> Maybe some of the oplock settings may help?
Oplocks are ok, and there is no network access on the DBFs, only local 
via RDP.

> Scandisk?
Scandisk Ok.

> Server load ok?
Well, the problem seems to only arrive when there are many users 
operating the system.
The links I wrote in the message refers to resources getting exhausted.

I was unable to reproduce, am only an spectator... And the users are 
getting angry!

Regards.

[[]] Maurício Faria

**Comment by prgwiz** [comment]
> > Maybe some of the oplock settings may help?
> Oplocks are ok, and there is no network access on the DBFs, only local
> via RDP.
>
> Your server is still sharing the files.  I would check the settings.
I wonder if some changes in RDP have happened that make the protocol less
efficient on the server now.  Even with idle clients.
Is you application windows or console mode?

**Comment by mauriciofaria** [comment]
Hi.

I was unable to manage the 9201 error issue.
In the end, I gave up from LetoDBf...

The app is a mix of console and Windows.
And, for me, RDP was the way to go.
And, as usual, each new version of Windows put more and more overhead in 
everything.

Regards.

Maurício Faria


Em 11/10/2022 04:58, Gerald Drouillard escreveu:

**Comment by elchs** [comment]
Hi Maurício,

in the sad VERY long end, after i saw this issue ... maybe helpful for others.

The first try would be creating a complete new index file *from the scratch*.
It doesn't sound for me as an OS resource problem or else ...


The error originated from Harbour ! RDD DBFCDX, just used by the LetoDbf server.
It is thrown in: harbour/src/rdd/dbfcdx/dbfcdx1.c, line 3933,
[ hb_cdxErrInternal( "hb_cdxPageSeekKey: wrong parent key." ); ]
after an internal index structure validation during a 'SEEK()'.

Harbour error 9201, if no specific cause given, means : "data integrity error"

** In our case for: "hb_cdxPageSeekKey: wrong parent key" **
it means a (possible wrongly ?) detected problem inside the B-tree index structure.

The question is if a 'race condition' in Harbour RDD for that specific validation,
when multiple user simultaneously changing data and by this way the index,
is possible ?? - maybe someone like to ask Harbour developer forum ...

A standalone tool to validate an index would be nice to have,
to rule out above suppose - don't know such.

The last part after the cryptic char is the search key for failed seek():
i.e.: seek <e;24;A;�640557    20220583>  ==> "640557    20220583".
If you do that seek() again after the crash, it should again throw that error.

---
By intention the LetoDBf server stops after such hard 'internal error',
as they should not appear.
But i agree, that not the *whole* server for all users should crash,
so i hacked into LetoDBf a workaround to catch these <9201> errors
and let only that specific connection crash. It's still not tested,
aka 'dry programming' ;-) as i never have experienced this error.

best regards
elch

**Comment by mauriciofaria** [comment]
Hi.

I gave up LetoDBf.
Every time error 9201 rises, the only solution I found was to rebuild 
the index.
Its unusable in production environment with that 9201 error with 
concurrent use of DBFs by LetoDBf and a normal application.
Probably if the DBFs are exclusive to LetoDBf this error does not occur, 
but I can not do this right now.
But very thanks for your attention anyway!!!

Regards.
Maurício Faria

Em 06/04/2023 07:31, elchs escreveu:

**Comment by elchs** [comment]
Hi Mauricio,

so finally no miracle :-)

! Important info was missing !
>> concurrent use of DBFs by LetoDBf and a normal application
SHARE_TABLES = 1

would have helped as long as no SAMBA service fiddeling around as it! is the only in world. 
Above setting would cost performance, and the way to go is a dedicated server.
So i can close this 'issue' ...

BTW, the date in bottom line looks older than yesterday

best regards
elch

**Comment by mauriciofaria** [comment]
Hi.

It was configured properly as    SHARE_TABLES = 1
And there was no SAMBA involved.
The concurrent use was on a local disk, without network.

Regards,
Maurício Faria


Em 12/04/2023 18:46, elchs escreveu:

**Comment by elchs** [comment]
Hi Mauricio,

i recently found out that locking cheme '3', in Harbour coined: DB_DBFLOCK_VFP  aka e.g. for FoxPro,
was never applied in LetoDBf -- and instead Harbour default used.
This maybe was the root of your index issues, as when that cheme was really needed.

I myself cannot try that fix because of missing non-Harbour app with such locking cheme,
and if Harbour's type 3 is compatible to that.
A quick test would be to try to lock with a leto test-snippet the same *record* [ RLOCK() ]
simultanously (hopefully) locked record in-usage for changes by the foreign app,
and vice versa ...

best regards
elch
