### ISSUE TITLE
Can´t compile lib with xharbour 1.2.3

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [elchs/LetoDBf#24]
MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
	IF EXIST "obj\api\letocl.obj" del obj\api\letocl.obj
	bcc32 -c -Iinclude;I:\XHARBOUR\include -d   -tWM -D__WIN32__ -D__CONSOLE__  -DUSE_PMURHASH=1 -D__LETO_C_API__=1 -DLETO_NO_MT=1 -DLETO_NO_THREAD=1 -oobj\api\letocl.obj source\client\letocl.c
Borland C++ 5.82 for Win32 Copyright (c) 1993, 2005 Borland
source\client\letocl.c:
Error E2209 I:\XHARBOUR\include\hbzlib.h 41: Unable to open include file '../source/rtl/zlib/zlib.h'
Warning W8017 I:\XHARBOUR\include\hbapirdd.h 125: Redefinition of 'HB_FT_TIME' is not identical
Error E2139 include\letocl.h 235: Declaration missing ;
Error E2139 include\letocl.h 286: Declaration missing ;
Error E2139 include\letocl.h 287: Declaration missing ;
Warning W8017 include\rddleto.ch 111: Redefinition of 'DBOI_TEMPORARY' is not identical
Warning W8072 source\client\letocl.c 1190: Suspicious pointer arithmetic in function leto_RecvFirst
Warning W8072 source\client\letocl.c 1418: Suspicious pointer arithmetic in function leto_Recv
Error E2451 source\client\letocl.c 1444: Undefined symbol 'zstream' in function leto_Recv
Warning W8072 source\client\letocl.c 1470: Suspicious pointer arithmetic in function leto_Recv
Warning W8072 source\client\letocl.c 1497: Suspicious pointer arithmetic in function leto_Recv
Error E2451 source\client\letocl.c 1504: Undefined symbol 'PHB_LZ4NET' in function leto_Recv
Error E2121 source\client\letocl.c 1504: Function call missing ) in function leto_Recv
Warning W8065 source\client\letocl.c 1544: Call to function 'LZ4_COMPRESSBOUND' with no prototype in function leto_Send
Error E2451 source\client\letocl.c 1594: Undefined symbol 'PHB_LZ4NET' in function leto_Send
Error E2121 source\client\letocl.c 1594: Function call missing ) in function leto_Send
Error E2121 source\client\letocl.c 1607: Function call missing ) in function leto_Send
Warning W8072 source\client\letocl.c 1630: Suspicious pointer arithmetic in function leto_Send
Warning W8065 source\client\letocl.c 2111: Call to function 'LZ4_decompress_safe' with no prototype in function leto_lz4Uncompress
Warning W8065 source\client\letocl.c 2117: Call to function 'LZ4_compress_fast' with no prototype in function leto_lz4Compress
Warning W8065 source\client\letocl.c 2167: Call to function 'LZ4_COMPRESSBOUND' with no prototype in function leto_CryptText
Warning W8072 source\client\letocl.c 2206: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2212: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2213: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2215: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2219: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2220: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2224: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2227: Suspicious pointer arithmetic in function leto_CryptText
Warning W8072 source\client\letocl.c 2354: Suspicious pointer arithmetic in function leto_replSkipBuf
Warning W8072 source\client\letocl.c 2368: Suspicious pointer arithmetic in function leto_replSkipBuf
Warning W8072 source\client\letocl.c 2374: Suspicious pointer arithmetic in function leto_replSkipBuf
Warning W8072 source\client\letocl.c 2409: Suspicious pointer arithmetic in function leto_AddTransBuffer
Warning W8072 source\client\letocl.c 2424: Suspicious pointer arithmetic in function leto_SearchTransList
Warning W8072 source\client\letocl.c 2425: Suspicious pointer arithmetic in function leto_SearchTransList
Warning W8072 source\client\letocl.c 2456: Suspicious pointer arithmetic in function leto_AddTransList
Warning W8072 source\client\letocl.c 2457: Suspicious pointer arithmetic in function leto_AddTransList
Warning W8072 source\client\letocl.c 3076: Suspicious pointer arithmetic in function leto_ParseRecord
Warning W8072 source\client\letocl.c 3467: Suspicious pointer arithmetic in function LetoConnectionOpen
Warning W8072 source\client\letocl.c 3481: Suspicious pointer arithmetic in function LetoConnectionOpen
Error E2451 source\client\letocl.c 3774: Undefined symbol 'zstream' in function LetoConnectionClose
Error E2451 source\client\letocl.c 3777: Undefined symbol 'PHB_LZ4NET' in function LetoConnectionClose
Error E2121 source\client\letocl.c 3777: Function call missing ) in function LetoConnectionClose
Error E2451 source\client\letocl.c 3781: Undefined symbol 'zstream' in function LetoConnectionClose
Warning W8075 source\client\letocl.c 4690: Suspicious pointer conversion in function LetoDbGetField
Warning W8072 source\client\letocl.c 4700: Suspicious pointer arithmetic in function LetoDbGetField
Warning W8072 source\client\letocl.c 4720: Suspicious pointer arithmetic in function LetoDbGetField
Warning W8012 source\client\letocl.c 4896: Comparing signed and unsigned values in function LetoDbPutField
Warning W8072 source\client\letocl.c 5088: Suspicious pointer arithmetic in function LetoDbGoTo
Error E2356 source\client\letocl.c 5329: Type mismatch in redeclaration of 'LetoDbSetRelation'
Error E2344 include\letocl.h 351: Earlier declaration of 'LetoDbSetRelation'
Error E2356 source\client\letocl.c 5367: Type mismatch in redeclaration of 'LetoDbCommit'
Error E2344 include\letocl.h 338: Earlier declaration of 'LetoDbCommit'
Warning W8072 source\client\letocl.c 5669: Suspicious pointer arithmetic in function leto_AddRecLock
Warning W8072 source\client\letocl.c 5684: Suspicious pointer arithmetic in function leto_DelRecLock
Warning W8072 source\client\letocl.c 5689: Suspicious pointer arithmetic in function leto_DelRecLock
Warning W8072 source\client\letocl.c 5751: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5753: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5754: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5756: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5757: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5759: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 5760: Suspicious pointer arithmetic in function LetoDbEval
Warning W8072 source\client\letocl.c 6395: Suspicious pointer arithmetic in function LetoVarSet
Warning W8072 source\client\letocl.c 7119: Suspicious pointer arithmetic in function LetoToggleZip
Error E2451 source\client\letocl.c 7134: Undefined symbol 'zstream' in function LetoToggleZip
Error E2451 source\client\letocl.c 7137: Undefined symbol 'PHB_LZ4NET' in function LetoToggleZip
Error E2121 source\client\letocl.c 7137: Function call missing ) in function LetoToggleZip
Error E2451 source\client\letocl.c 7141: Undefined symbol 'zstream' in function LetoToggleZip
Error E2451 source\client\letocl.c 7147: Undefined symbol 'zstream' in function LetoToggleZip
Error E2451 source\client\letocl.c 7148: Undefined symbol 'zstream' in function LetoToggleZip
Warning W8065 source\client\letocl.c 7148: Call to function 'hb_lz4netOpen' with no prototype in function LetoToggleZip
Error E2451 source\client\letocl.c 7153: Undefined symbol 'zstream' in function LetoToggleZip
Error E2228 source\client\letocl.c 7153: Too many error or warning messages in function LetoToggleZip
*** 26 errors in Compile ***

** error 1 ** deleting obj\api\letocl.obj

**Comment by elchs** [comment]
Hi Numerabilis,

building LetoDBf CLIENT-side lib for xHarbour apps is not as convenient as for Harbour.

For sure you missed the "full" param for that batch file,
[ also sure you do not want the *C-API* lib ]
and haven't uncommented the line in makefile.bc for xHarbour.

Check Readme.txt for 2.1 and 2.5 (xBuilder!).

MOST IMPORTANT: i can't really give help for xHarbour,
check xHB specific forums as some were able to build the *client* ! library ...

regards
elch
