### ISSUE TITLE
WARNING: You need to implement LZ4_DEPRECATED for this compiler

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [elchs/LetoDBf#25]
>    XCC: can't compile 3rd party 'lz4.c', compile it with PellesC >= 4.5 manually,
>         and replace it in list of files for xBuilder with resulting 'lz4.obj':
>         pocc.exe -Fo"obj\lz4.obj" -Ot -I"include" -I"source\3rd\lz4\lib" -I%PATH_XHB%"\include"
>                  -I%PATH_POCC%"\Include" -I%PATH_POCC%"\include\Win" "source\3rd\lz4\lib\lz4.c"

```
C:\PROGRAMAS\LetoDBf>pocc.exe -Fo"obj\lz4.obj" -Ot -I"include" -I"source\3rd\lz4\lib" -I"C:\XHB123\include" -I"C:\PellesC\Include" -I"C:\PellesC\Include\Win" "source\3rd\lz4\lib\lz4.c"
WARNING: You need to implement LZ4_DEPRECATED for this compiler
```
I have PellesC v11.0 stable version.
How can I compile it with PellesC? It´s not working.

**Comment by elchs** [comment]
Hi Numerabilis,

we have generally to differ between 'warning' and 'error'.
Above is a _warning_, and the wanted .obj should have been created ?!

What does this warning in this case means ?
-- that Pelles-C is not treated especially, aka not using advanced features of other C-compilers.

Moreover, there are no warnings - else as the warning, that warning messages are not suppressed :-)
From the source of LZ4:
"  Should these warnings messages be a problem,
   it is generally possible to disable them,
   with -Wno-deprecated-declarations for gcc
   or _CRT_SECURE_NO_WARNINGS in Visual for example. ... "
---
I won't even look up for a special syntax for Pelles, if adding a:
-Wno-deprecated-declarations
in the instruction line to compile the object would not suppress that warning ...

**Comment by AndersonCardosoSilva-BR** [comment]
Thanks for the answer.
I noticed that obj was generated indeed.
I downgraded to PellesC v8.0 because you said you had tested ok on it.
