### ISSUE TITLE
Fatal F1003 C:\PellesC\Include\stdarg.h 9: Error directive: <stdarg.h> need POCC version 10.0 or higher

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [elchs/LetoDBf#26]
make_b32 full

>  MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
> 	bcc32 -c -Iinclude;C:\XHB123\include;C:\PellesC\Include -d   -tWM -D__WIN32__ -D__CONSOLE__  -DUSE_PMURHASH=1 -oobj\b32\letocl.obj source\client\letocl.c
> Borland C++ 5.82 for Win32 Copyright (c) 1993, 2005 Borland
> source\client\letocl.c:
> Fatal F1003 C:\PellesC\Include\stdarg.h 9: Error directive: <stdarg.h> need POCC version 10.0 or higher
> *** 1 errors in Compile ***
> 
> ** error 1 ** deleting obj\b32\letocl.obj

I have installed **PellesC v11.0** but it seems it´s telling I have v9 in this error

In make_b32.bat I changed: SET HB_PATH=C:\XHB123
In makefile.bc I only uncommented:
```
# uncomment next line if you want to build letodb with xharbour
XHARBOUR = yes
```
What should I do now? Nobody is talking about LetoDBF with xHarbour
I am using xHarbour v1.2.3, BCC58 and PellesC v11.0

**Comment by elchs** [comment]
Hi _Numerabilis_,

this part here:
-Iinclude;C:\XHB123\include;C:\PellesC\Include
disturbs BCC, telling it to use Pelles include files, maybe even beforehand the own ones of BCC.

Moreover, you must have added that yourself, as my distributed makefile says:
INCLUDE_DIR = include;$(HRB_DIR)\include

Mixed C-compilers setup isn't an easy thing, maybe especially if 20 years old BCC is in between ...

---
below redacted, belongs more to your other issue:

let us make the living with xHb and Windows a bit easier ;-),
and to exclude - or better: just not to include - LZ4 compression,
but instead use standard zLib compression if needed.

! The server itself must be build with Harbour, not xHb, because of minor differences e.g. about threading.
In the second line of letodb[svc].hbp you see LZ4 is not included for BCC.
To be on the save side, put a '#' at front, then no compiler will include LZ4 for the server.
Then build it using Harbour's hbmk2 make-tool.

Now for building the lib for xHb.
I don't see there any mention of LZ4 in the makefile.bc, but e,g, in the rddleto.lib.xbp
Check for C-compiler flag 'USE_LZ4' and any directories containing 'lz4',
and carefully remove that elements/ lines in any ! makefile ! -- but never ever in the source itself

hopefully, may report again ...
elch

**Comment by AndersonCardosoSilva-BR** [comment]
Ok, only BCC58 with xHb 123 now:

> MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
> 	bcc32 -c -Iinclude;C:\XHB123\include;C:\BCC58\Include -d   -tWM -D__WIN32__ -D__CONSOLE__  -DUSE_PMURHASH=1 -oobj\b32\letocl.obj source\client\letocl.c
> Borland C++ 5.82 for Win32 Copyright (c) 1993, 2005 Borland
> source\client\letocl.c:
> Warning W8017 C:\XHB123\include\hbapirdd.h 125: Redefinition of 'HB_FT_TIME' is not identical
> Error E2139 include\letocl.h 235: Declaration missing ;
> Error E2139 include\letocl.h 286: Declaration missing ;
> Error E2139 include\letocl.h 287: Declaration missing ;
> Warning W8017 include\rddleto.ch 111: Redefinition of 'DBOI_TEMPORARY' is not identical
> Warning W8072 source\client\letocl.c 1190: Suspicious pointer arithmetic in function leto_RecvFirst
> Warning W8072 source\client\letocl.c 1418: Suspicious pointer arithmetic in function leto_Recv
> Error E2451 source\client\letocl.c 1444: Undefined symbol 'zstream' in function leto_Recv
> Warning W8072 source\client\letocl.c 1470: Suspicious pointer arithmetic in function leto_Recv
> Warning W8072 source\client\letocl.c 1497: Suspicious pointer arithmetic in function leto_Recv
> Error E2451 source\client\letocl.c 1504: Undefined symbol 'PHB_LZ4NET' in function leto_Recv
> Error E2121 source\client\letocl.c 1504: Function call missing ) in function leto_Recv
> Warning W8065 source\client\letocl.c 1544: Call to function 'LZ4_COMPRESSBOUND' with no prototype in function leto_Send
> Error E2451 source\client\letocl.c 1594: Undefined symbol 'PHB_LZ4NET' in function leto_Send
> Error E2121 source\client\letocl.c 1594: Function call missing ) in function leto_Send
> Error E2121 source\client\letocl.c 1607: Function call missing ) in function leto_Send
> Warning W8072 source\client\letocl.c 1630: Suspicious pointer arithmetic in function leto_Send
> Warning W8065 source\client\letocl.c 2116: Call to function 'LZ4_decompress_safe' with no prototype in function leto_lz4Uncompress
> Warning W8065 source\client\letocl.c 2122: Call to function 'LZ4_compress_fast' with no prototype in function leto_lz4Compress
> Warning W8065 source\client\letocl.c 2172: Call to function 'LZ4_COMPRESSBOUND' with no prototype in function leto_CryptText
> Warning W8072 source\client\letocl.c 2211: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2217: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2218: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2220: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2224: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2225: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2229: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2232: Suspicious pointer arithmetic in function leto_CryptText
> Warning W8072 source\client\letocl.c 2359: Suspicious pointer arithmetic in function leto_replSkipBuf
> Warning W8072 source\client\letocl.c 2373: Suspicious pointer arithmetic in function leto_replSkipBuf
> Warning W8072 source\client\letocl.c 2379: Suspicious pointer arithmetic in function leto_replSkipBuf
> Warning W8072 source\client\letocl.c 2414: Suspicious pointer arithmetic in function leto_AddTransBuffer
> Warning W8072 source\client\letocl.c 2429: Suspicious pointer arithmetic in function leto_SearchTransList
> Warning W8072 source\client\letocl.c 2430: Suspicious pointer arithmetic in function leto_SearchTransList
> Warning W8072 source\client\letocl.c 2461: Suspicious pointer arithmetic in function leto_AddTransList
> Warning W8072 source\client\letocl.c 2462: Suspicious pointer arithmetic in function leto_AddTransList
> Warning W8072 source\client\letocl.c 3083: Suspicious pointer arithmetic in function leto_ParseRecord
> Warning W8072 source\client\letocl.c 3190: Suspicious pointer arithmetic in function leto_elch
> Warning W8072 source\client\letocl.c 3217: Suspicious pointer arithmetic in function leto_elch
> Warning W8072 source\client\letocl.c 3237: Suspicious pointer arithmetic in function leto_elch
> Warning W8072 source\client\letocl.c 3474: Suspicious pointer arithmetic in function LetoConnectionOpen
> Warning W8072 source\client\letocl.c 3488: Suspicious pointer arithmetic in function LetoConnectionOpen
> Error E2451 source\client\letocl.c 3630: Undefined symbol 'hThread' in function LetoConnectionOpen
> Error E2451 source\client\letocl.c 3632: Undefined symbol 'hThread' in function LetoConnectionOpen
> Error E2451 source\client\letocl.c 3633: Undefined symbol 'hThread' in function LetoConnectionOpen
> Warning W8065 source\client\letocl.c 3767: Call to function 'hb_fsPipeWrite' with no prototype in function LetoConnectionClose
> Error E2451 source\client\letocl.c 3781: Undefined symbol 'zstream' in function LetoConnectionClose
> Error E2451 source\client\letocl.c 3784: Undefined symbol 'PHB_LZ4NET' in function LetoConnectionClose
> Error E2121 source\client\letocl.c 3784: Function call missing ) in function LetoConnectionClose
> Error E2451 source\client\letocl.c 3788: Undefined symbol 'zstream' in function LetoConnectionClose
> Warning W8075 source\client\letocl.c 4698: Suspicious pointer conversion in function LetoDbGetField
> Warning W8072 source\client\letocl.c 4708: Suspicious pointer arithmetic in function LetoDbGetField
> Warning W8072 source\client\letocl.c 4728: Suspicious pointer arithmetic in function LetoDbGetField
> Warning W8072 source\client\letocl.c 5099: Suspicious pointer arithmetic in function LetoDbGoTo
> Error E2356 source\client\letocl.c 5379: Type mismatch in redeclaration of 'LetoDbSetRelation'
> Error E2344 include\letocl.h 352: Earlier declaration of 'LetoDbSetRelation'
> Error E2356 source\client\letocl.c 5417: Type mismatch in redeclaration of 'LetoDbCommit'
> Error E2344 include\letocl.h 339: Earlier declaration of 'LetoDbCommit'
> Warning W8072 source\client\letocl.c 5719: Suspicious pointer arithmetic in function leto_AddRecLock
> Warning W8072 source\client\letocl.c 5734: Suspicious pointer arithmetic in function leto_DelRecLock
> Warning W8072 source\client\letocl.c 5739: Suspicious pointer arithmetic in function leto_DelRecLock
> Warning W8072 source\client\letocl.c 5801: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5803: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5804: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5806: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5807: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5809: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 5810: Suspicious pointer arithmetic in function LetoDbEval
> Warning W8072 source\client\letocl.c 6445: Suspicious pointer arithmetic in function LetoVarSet
> Warning W8072 source\client\letocl.c 7169: Suspicious pointer arithmetic in function LetoToggleZip
> Error E2451 source\client\letocl.c 7184: Undefined symbol 'zstream' in function LetoToggleZip
> Error E2451 source\client\letocl.c 7187: Undefined symbol 'PHB_LZ4NET' in function LetoToggleZip
> Error E2121 source\client\letocl.c 7187: Function call missing ) in function LetoToggleZip
> Error E2451 source\client\letocl.c 7191: Undefined symbol 'zstream' in function LetoToggleZip
> Error E2451 source\client\letocl.c 7197: Undefined symbol 'zstream' in function LetoToggleZip
> Error E2228 source\client\letocl.c 7197: Too many error or warning messages in function LetoToggleZip
> *** 26 errors in Compile ***
> 
> ** error 1 ** deleting obj\b32\letocl.obj

Note, when I use xbuildw with xCC and that I put the path for PellesC it says that compile was successfull but I can´t find where the LIB is...
By the way, a LIB compiled with PellesC could be linked using BCC58 afterwards?

**Comment by elchs** [comment]
Hi Numerabilis,

> Note, when I use xbuildw with xCC and that I put the path for PellesC it says that compile was successfull but I can´t find where the LIB is...

THAT's should be your way to go. These old makefiles are nowadays only used by me for the C-API,
and btw; not for BCC ;-)

* The resulting lib is in the 'lib' directory of LetoDBf. *
So to include that PATH in xBuilder script for libs -- or -- move the lib into the directory with xHB libs.

> By the way, a LIB compiled with PellesC could be linked using BCC58 afterwards?

Don't know -- maybe try it -- if it builds an executable, try to run it ...
But i wouldn't mix that BCC stuff with other C-compilers, and never had v5.8 at hand ...

regards
elch

**Comment by AndersonCardosoSilva-BR** [comment]
I didn´t find the lib anywhere... :(
Buildw says "successfull" but not ok. I couldn´t make any test...

**Comment by elchs** [comment]
Hi Numerabilis,

x! day totally Internet blackout by my provider, just beeing fresh online,
expect a coming answer ...

elch
