### ISSUE TITLE
BOF() not being reset after a dbgoto()

### ISSUE THREAD

**Issue by abebuch** [elchs/LetoDBf#3]
Hi,

please try this 

go top
saverec := recn()
skip -1
? bof()
goto saverec
? bof()

**Comment by elchs** [comment]
Hi abebuch,

a special case when the active record did not change,
as long the cache is not timed out.
( in example you are always at record no 1 )
Thanks for pointing out, should be fixed.

best regards
Rolf

**Comment by abebuch** [comment]
tnx a lot.
