### ISSUE TITLE
INDEX ... FOR condition

### ISSUE THREAD

**Issue by AndersonCardosoSilva-BR** [elchs/LetoDBf#31]
> Error LETO/1003  : Variable does not exist XANO
This error came out with LETO_DBF.
xANO is a public variable and it is seen (exist) in debug runtime normally. It is used in a temp index with a for condition.
_The code is:_
```
   SELECT EMP
   cRANDOM1  := ALLTRIM(STR(RAN(9999)))
   fINDEX1   := xTEMP+"TEMP" + cRANDOM1 + INDEXEXT()
   INDEX ON CNPJ+ANO TAG TEMP TO (fINDEX1) ;
         FOR ANO=xANO ;
         ADDITIVE TEMPORARY
```
That error alert gives me 2 options: QUIT or RETRY.
If I RETRY it works ok...
How can I stop this alert?

> The FOR expression cannot exceed 250 characters in length. RDDs that do not support a FOR condition when creating indexes generate a runtime error when this option is used. 

Anyway it creates the index correctly if I RETRY so maybe it could be fixed or I could make an error handler to make this RETRY automatically but I don´t know how.

**Comment by elchs** [comment]
Hi Numerabilis,

marked as question !, it is NO bug.                       

> Error LETO/1003 : Variable does not exist XANO

Index orders are created AT SERVER side.
The server does NOT know variables of your application --> 'xANO' is undefined.
--> this index can NOT ! be created, as the 'FOR' expression is invalid AT SERVER.

The RunTimeError ALERT() is for convenience, alternative would be: only QUIT()
When choosing: RETRY, it  means --> continue *without* that index.

--
? So how to work around this limit, and keep [x]Harbour conform source ?
This can be done by using OrdCondSet() + OrdCreate() direcctly.
Check 'include/std.ch', there your 'INDEX ON' *command* is pre-processed into these functions.

--
Example, by assuming 'xANO' is a numeric integer ??
Note about formula: &("{||"+c+"}") -- creates at runtime a codeblock from a string expression.

--snip--
LOCAL cKey, cFor
...
>   cRANDOM1  := ALLTRIM(STR(RAN(9999)))
>   fINDEX1   := xTEMP+"TEMP" + cRANDOM1 + INDEXEXT()

   cKey := "CNPJ+ANO"
   cFor := "ANO=" + STR(xANO,4,0)

   ordCondSet( cFor, &("{||"+ cFor +"}"), /*all*/, /*b_while*/, ;
               /*eval*/, /*every*/, RecNo(), /*next*/, /*rec*/, ;
               /*rest*/, /*descend*/, /*NIL*/, ;
               .T. /*add*/, /*cur*/, /*cust*/, /*noopt*/, ;
               /*c_while*/, .T. /*mem*/, /*filter*/, /*ex*/ )

   ordCreate( fIndex1 /*bag*/, "TEMP" /*tag*/, cKey, &("{||"+ cKey +"}"), /*unique*/ )
--snip--

Note: above example should work for [x]Harbour and *any* RDD,
LetoDBf don't need the codeblocks, as these cannot be transmitted to the server. 
And yes, there are 20! possible arguments for OrdCondSet() ...

---
Another solution would be using the Leto_VAR() system. That are <network-wide> variables,
which can bet set and read not only by your application, but also by the LetoDBf server,
and even by other applications - so these are no app PRIVATE/PUBLIC, but: 'UNIVERSE'-wide visible ;-)
Doing so, you will end up with code ONLY working for LetoDBf
-- and one of my aims is to stay Harbour/other RDD conform as far as possible.

*ALSO* this makes no sense for index orders !!
As when your 'xANO' value changes, the index order gets inconsistent, even for a temporary index.

Leto_Var() technic is used <automatic> without source changes by the client library, when HB_SET_FORCEOPT is set to .T.,
for !! SET FILTER TO !! expressions - for them it makes sense to dynamically change the condition.
But this is a very another topic, check Readme first ...

best regards
elch

**Comment by elchs** [comment]
addendum,
my asterisks in code snippet got robbed as font attribute ;-(

[snip.txt](https://github.com/elchs/LetoDBf/files/11727798/snip.txt)

**Comment by AndersonCardosoSilva-BR** [comment]
Hi Elchs,

Thank you for your clarifying explanation!
Actually, I use this tecnique as an alternative to SET FILTER to speed up my application without a database server using temp index files. 
Maybe I don´t need to do it anymore as I am using LETODBF, isn´t it? SET FILTER will run at server side faster, right? No data traveling around the net, correct? 

If I use SET FILTER I would have the same problem or it´s a good idea to keep these temp index files?
xANO is a public variable used to filter the working year, in english would be xYEAR.

`xANO    := STR(YEAR(DATE()), 4)`

That is the default, but user can change it. I´m wondering to include a field ANO in the user´s database so it will be save the last working year the user selected, I think that should work better, isn´t it?

**Comment by AndersonCardosoSilva-BR** [comment]
```
      INDEX ON MODALIDADE+ANO+STRZERO(NUMERO,3)+COMPL TAG TEMP TO (fINDEX) ;
            FOR ANO=US->ANO  ;
            ADDITIVE TEMPORARY
```
This is working better for me.
I am storing the current working year in a user field US->ANO.
