### ISSUE TITLE
Unrecoverable error 9023 at client side

### ISSUE THREAD

**Issue by SergyRus** [elchs/LetoDBf#5]
As suggested to me by Viktor, I open topic here.

Details is here: https://groups.google.com/forum/#!topic/harbour-users/iuptZoeca0k

Strange, unpredictable "Unrecoverable errors 9023" in client app.

**Comment by SergyRus** [comment]
Got new one
Info attached
[INFO.zip](https://github.com/elchs/LetoDBf/files/1204915/INFO.zip)

**Comment by SergyRus** [comment]
Got two errors, info attached.
As I can see, the most of them happens in few minutes after program/system start...

[info1.zip](https://github.com/elchs/LetoDBf/files/1207692/info1.zip)
[info2.zip](https://github.com/elchs/LetoDBf/files/1207693/info2.zip)

**Comment by SergyRus** [comment]
Two errors was today
In both cases - in 2..3 minutes after program first start. 
Then, till the evening all works fine.

[Info1.zip](https://github.com/elchs/LetoDBf/files/1212593/Info1.zip)
[Info2.zip](https://github.com/elchs/LetoDBf/files/1212594/Info2.zip)

**Comment by SergyRus** [comment]
Yesterday there were no errors.
Today, as usual - twice. Both in few minutes after start.

[info1.zip](https://github.com/elchs/LetoDBf/files/1217376/info1.zip)
[info2.zip](https://github.com/elchs/LetoDBf/files/1217377/info2.zip)

**Comment by SergyRus** [comment]
Got 2+1 errors

[info1.zip](https://github.com/elchs/LetoDBf/files/1221978/info1.zip)
[info2.zip](https://github.com/elchs/LetoDBf/files/1221979/info2.zip)

**Comment by SergyRus** [comment]
Two crashes after start

[info1.zip](https://github.com/elchs/LetoDBf/files/1224564/info1.zip)
[info2.zip](https://github.com/elchs/LetoDBf/files/1224565/info2.zip)

**Comment by elchs** [comment]
Sergy just reportet: gone after server hardware change
