### ISSUE TITLE
Compiling on FreeBSD

### ISSUE THREAD

**Issue by mallavoodoo** [elchs/LetoDBf#7]
Hi;

I'm attempting to compile letodbf on FreeBSD. I have harbour installed and working.

Here is my system:

- FreeBSD 11.1-STABLE
- Harbour Make (hbmk2) 3.4.0dev () (2017-09-12 17:36)

Output of letodbf compilation:
[/Dbase/Leto/letodbf]>hbmk2 rddleto.hbp letodb.hbp
hbmk2: Compiling Harbour sources...
hbmk2: Compiling...
hbmk2: Creating static library... /usr/local/sbin/harbour/lib/librddleto.a

My letodb.ini:

Server = 10.3.51.45
IP = 10.3.51.45  
Port = 2812
DataPath = /home/lap/DBF
Logpath = /var/log
Default_Driver = NTX
;Lock_Scheme = 6
;Memo_Type = FPT
Share_Tables = 0
No_Save_WA = 1
Lower_Path = 0
EnableFileFunc = 1
EnableAnyExt = 1
Allow_UDF = 1
Pass_for_Login = 0
Pass_for_Manage = 0
Pass_for_Data = 0
;Pass_File = "leto_users"
Cache_Records = 21
;Max_Vars_Number = 1000
;Max_Var_Size = 67108864
;Tables_Max  = 999
;Users_Max = 99
Debug = 25
Optimize = 1
;AutOrder = 0
;ForceOpt = 0
;TimeOut = 360
;Zombie_Check = 0
;Server_User = advantage
;Server_UID = 1000
;Server_GID = 4
;BC_Services = letodb;
;BC_Interface = eth2
;BC_Port = 2812
DataBase = /
Backup = /tmp/backup
Mask = *.dbf,*.dbt,*.ntx
Lock = 1
Seconds = 30
Wait = 1
ArcCmd = tar -cvzf /tmp/backup/leto.tar.gz /tmp/backup/*

My active sockets:

[/Dbase/Leto/letodbf]>netstat -an | grep LIST
tcp4       0      0 127.0.0.1.6010         *.*                    LISTEN
tcp4       0      0 127.0.0.1.25           *.*                    LISTEN
tcp4       0      0 *.22                   *.*                    LISTEN
tcp4       0      0 *.139                  *.*                    LISTEN
tcp4       0      0 *.445                  *.*                    LISTEN

/var/log/letodbf.log:

10.09.2017 14:40:06       LetoDBf Server try to start ...
10.09.2017 14:40:06       UDF file: /usr/local/sbin/harbour/bin/letoudf.hrb not present.
10.09.2017 14:40:06 INFO: LetoDBf Server 3.00, will run at IP 10.3.51.45:2812 ( internal also used :2813 )
10.09.2017 14:40:06 INFO: DataPath=/home/lap/DBF, ShareTables=0, NoSaveWA=1, max database=999
10.09.2017 14:40:06 INFO: LoginPassword=0, CacheRecords=21, LockExtended=0
10.09.2017 14:40:06 DEBUG second socket: 3 for errors established
10.09.2017 14:40:06 DEBUG thread3() with pipe handle: 4 started .. 
10.09.2017 14:40:06 DEBUG thread3() ending ..
10.09.2017 14:40:07       Server has been closed.

letodbf starts but exits a second later.

The original letodb runs fine. 

Any ideas?

**Comment by mallavoodoo** [comment]
To answer my own question, I found out what was wrong. 

In FreeBSD,

     struct timeval {
             long    tv_sec;         /* seconds since Jan. 1, 1970 */
             long    tv_usec;        /* and microseconds */
     };

OBS -  tv_usec can only go as high as 999999!.

On leto_2.c, there were declarations like:

         MicroWait.tv_sec = 0;
         MicroWait.tv_usec = 2000000;
and
         MicroWait.tv_sec = 0;
         MicroWait.tv_usec = 1500000; 

that were issuing errno = 22 (timeout), i.e., tv_usec were being ignored.
All I had to do was to change those to:

         MicroWait.tv_sec = 2;
         MicroWait.tv_usec = 0;
and
         MicroWait.tv_sec = 1;
         MicroWait.tv_usec = 500000; 

And the server worked correctly.

**Comment by mallavoodoo** [comment]
To answer my own question, I found out what was wrong. 

In FreeBSD,

     struct timeval {
             long    tv_sec;         /* seconds since Jan. 1, 1970 */
             long    tv_usec;        /* and microseconds */
     };

OBS -  tv_usec can only go as high as 999999!.

On leto_2.c, there were declarations like:

         MicroWait.tv_sec = 0;
         MicroWait.tv_usec = 2000000;
and
         MicroWait.tv_sec = 0;
         MicroWait.tv_usec = 1500000; 

that were issuing errno = 22 (timeout), i.e., tv_usec were being ignored.
All I had to do was to change those to:

         MicroWait.tv_sec = 2;
         MicroWait.tv_usec = 0;
and
         MicroWait.tv_sec = 1;
         MicroWait.tv_usec = 500000; 

And the server worked correctly.

**Comment by elchs** [comment]
Hi Mario,

your Fix applied, Thanks! -- that looks hard to track, my respect, WOW!
Moreover I looked in a different branch, with sockets using poll(), not! select().

See note in Changelog.txt, where to switch with maybe an additional:
#if defined ( HB_OS_BSD ) || ( ... )
and there is also a post at Harbour list about ...

BEST regards
Rolf

**Comment by mallavoodoo** [comment]
On Sun, 24 Dec 2017 06:23:32 -0800
elchs <notifications@github.com> wrote:

> Hi Mario,
> 
> your Fix applied, Thanks! -- that looks hard to track, my respect,
> WOW! Moreover I looked in a different branch, with sockets using
> poll(), not! select().
> 
> See note in Changelog.txt, where to switch with maybe an additional:
> #if defined ( HB_OS_BSD ) || ( ... )
> and there is also a post at Harbour list about ...
> 
> BEST regards
> Rolf
> 

You're welcome, Rolf! I'm glad I could give this minuscule help on this
wonderful masterpiece of yours.

Indeed it was hard to track but the timeout error (OS) gave me the
clue I needed to find it.

Happy 2018 !
-- 
Mario Lobo
http://www.mallavoodoo.com.br
FreeBSD since 2.2.8 [not Pro-Audio.... YET!!]

"UNIX was not designed to stop you from doing stupid things, 
because that would also stop you from doing clever things."
