### ISSUE TITLE
LetoDBf for xHarbour

### ISSUE THREAD

**Issue by patrickmast** [elchs/LetoDBf#8]
Hey Rolf,

Do you have a build script for xHarbour Builder for LetoDBf?
Thanks!

Patrick

**Comment by elchs** [comment]
info to others:

after some help by Patrick, Thanks! a lot, and a bunch of changes,
the client library RDD should be build-able for xHB/ xBuilder.

Server itself must ever be build by Harbour.
Look for new chapter in Readme.txt for xHarbour.

Now intense tests should follow, basic request from Patrick looks solved.

best Regards, elch
